// See https://aka.ms/new-console-template for more information

using System.CommandLine;
using Albatross.CommandLine;
using Microsoft.Extensions.DependencyInjection;
using BPOR.Domain;
using Microsoft.Extensions.Configuration;

var hostBuilder = new CommandHost("RMS Pipeline Ingest Tool")
    .ConfigureHost(builder =>
    {
        builder.ConfigureHostConfiguration(config => config
            .AddCommandLine(args)
            .AddEnvironmentVariables());
        builder.AddNihrConfiguration();
    })
    .RegisterServices(RegisterServices)
    .AddCommands(); // Generated by source generator
hostBuilder.CommandBuilder.RootCommand.TreatUnmatchedTokensAsErrors = false;

await using var host = hostBuilder.Parse(args).Build();

return await host.InvokeAsync();

static void RegisterServices(ParseResult result, IServiceCollection services) 
{
    services.RegisterCommands();  // Generated by source generator
    services.AddRmsDatabase();
}