//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPOR.Rms.Ms4.Views.StudyRequest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StudyRequestEditResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudyRequestEditResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPOR.Rms.Ms4.Views.StudyRequest.StudyRequestEditResources", typeof(StudyRequestEditResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 1: Overview.
        /// </summary>
        internal static string Section1Caption {
            get {
                return ResourceManager.GetString("Section1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 2: Study details.
        /// </summary>
        internal static string Section2Caption {
            get {
                return ResourceManager.GetString("Section2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 3: Sponsorship.
        /// </summary>
        internal static string Section3Caption {
            get {
                return ResourceManager.GetString("Section3Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 4: Participant details.
        /// </summary>
        internal static string Section4Caption {
            get {
                return ResourceManager.GetString("Section4Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 5: Check your answers.
        /// </summary>
        internal static string Section5Caption {
            get {
                return ResourceManager.GetString("Section5Caption", resourceCulture);
            }
        }
    }
}
