// <auto-generated />
using System;
using Dynamo.Stream.Handler.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dynamo.Stream.Handler.Migrations
{
    [DbContext(typeof(ParticipantDbContext))]
    [Migration("20231201094830_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dynamo.Stream.Handler.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CommunicationLanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DailyLifeImpactId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("Disability")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("EthnicBackground")
                        .HasColumnType("longtext");

                    b.Property<string>("EthnicGroup")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool?>("GenderIsSameAsSexRegisteredAtBirth")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("HasLongTermCondition")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LandlineNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("NHSNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("RegistrationConsent")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RegistrationConsentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RemovalOfConsentRegistrationAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CommunicationLanguageId");

                    b.HasIndex("DailyLifeImpactId");

                    b.HasIndex("GenderId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Dynamo.Stream.Handler.Entities.ParticipantAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLine4")
                        .HasColumnType("longtext");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<string>("Postcode")
                        .HasColumnType("longtext");

                    b.Property<string>("Town")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.ToTable("ParticipantAddress");
                });

            modelBuilder.Entity("Dynamo.Stream.Handler.Entities.ParticipantHealthCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HealthConditionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("HealthConditionId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ParticipantHealthCondition");
                });

            modelBuilder.Entity("Dynamo.Stream.Handler.Entities.ParticipantIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdentifierTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdentifierTypeId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ParticipantIdentifiers");
                });

            modelBuilder.Entity("Dynamo.Stream.Handler.Entities.RefData.CommunicationLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("SysRefCommunicationLanguage", (string)null);
                });

            modelBuilder.Entity("Dynamo.Stream.Handler.Entities.RefData.DailyLifeImpact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("SysRefDailyLifeImpact", (string)null);
                });

            modelBuilder.Entity("Dynamo.Stream.Handler.Entities.RefData.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("SysRefGender", (string)null);
                });

            modelBuilder.Entity("Dynamo.Stream.Handler.Entities.RefData.HealthCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("SysRefHealthCondition", (string)null);
                });

            modelBuilder.Entity("Dynamo.Stream.Handler.Entities.RefData.IdentifierType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("SysRefIdentifierType", (string)null);
                });

            modelBuilder.Entity("Dynamo.Stream.Handler.Entities.Participant", b =>
                {
                    b.HasOne("Dynamo.Stream.Handler.Entities.RefData.CommunicationLanguage", "CommunicationLanguage")
                        .WithMany()
                        .HasForeignKey("CommunicationLanguageId");

                    b.HasOne("Dynamo.Stream.Handler.Entities.RefData.DailyLifeImpact", "DailyLifeImpact")
                        .WithMany()
                        .HasForeignKey("DailyLifeImpactId");

                    b.HasOne("Dynamo.Stream.Handler.Entities.RefData.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.Navigation("CommunicationLanguage");

                    b.Navigation("DailyLifeImpact");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("Dynamo.Stream.Handler.Entities.ParticipantAddress", b =>
                {
                    b.HasOne("Dynamo.Stream.Handler.Entities.Participant", "Participant")
                        .WithOne("Address")
                        .HasForeignKey("Dynamo.Stream.Handler.Entities.ParticipantAddress", "ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Dynamo.Stream.Handler.Entities.ParticipantHealthCondition", b =>
                {
                    b.HasOne("Dynamo.Stream.Handler.Entities.RefData.HealthCondition", "HealthCondition")
                        .WithMany()
                        .HasForeignKey("HealthConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dynamo.Stream.Handler.Entities.Participant", "Participant")
                        .WithMany("HealthConditions")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCondition");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Dynamo.Stream.Handler.Entities.ParticipantIdentifier", b =>
                {
                    b.HasOne("Dynamo.Stream.Handler.Entities.RefData.IdentifierType", "Type")
                        .WithMany()
                        .HasForeignKey("IdentifierTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dynamo.Stream.Handler.Entities.Participant", "Participant")
                        .WithMany("ParticipantIdentifiers")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Dynamo.Stream.Handler.Entities.Participant", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("HealthConditions");

                    b.Navigation("ParticipantIdentifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
