name: Stream Ingestor Manual Deploy Dev

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials - All
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.NIHR_GITHUB_ACTIONS_IAM_ID }}
          aws-secret-access-key: ${{ secrets.NIHR_GITHUB_ACTIONS_IAM_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Run Number and Build Id
        run: echo ${{ github.run_number }}-${{ github.run_id }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Add Nuget Source
        run: dotnet nuget add source --username ${{ secrets.NUGET_PACKAGE_USERNAME }} --password ${{ secrets.NUGET_PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pa-nihr-crn/index.json"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Deploy
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet lambda deploy-function --region ${{ secrets.AWS_REGION }} -pl ./Dynamo.Stream.Ingestor/src/Dynamo.Stream.Ingestor crnccd-lambda-dev-dte-participant-ingestor --function-role crnccd-iam-dev-dte-role -ev "ASPNETCORE_ENVIRONMENT=Production;DTE_BUILD_STRING=dev-${{ github.run_number }}-${{ github.run_id }};AWS_SECRET_MANAGER_SECRET_NAME=crnccd-crnccd-secret-dev-dte-stream-ingestor" --function-publish true

      - name: Update alias to point to new version
        run: |
          VERSION=$(aws lambda list-versions-by-function --function-name crnccd-lambda-dev-dte-participant-ingestor --query "Versions[-1]" | jq -r .Version)
          aws lambda update-alias --function-name crnccd-lambda-dev-dte-participant-ingestor --name main --function-version $VERSION
