name: Stream Handler Staged Deploy
on:
  workflow_dispatch:

jobs:
  dev_build_test_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BPOR
    environment: DEV
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials - All
        # if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.NIHR_GITHUB_ACTIONS_IAM_ID }}
          aws-secret-access-key: ${{ secrets.NIHR_GITHUB_ACTIONS_IAM_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Run Number and Build Id
        run: echo ${{ github.run_number }}-${{ github.run_id }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Add Nuget Source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pa-nihr-crn/index.json"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Deploy
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet lambda deploy-function --region ${{ secrets.AWS_REGION }} -pl ./BPOR.Registration.Stream.Handler/src/BPOR.Registration.Stream.Handler crnccd-lambda-dev-dte-participant-stream --function-role crnccd-iam-dev-dte-role -ev "ASPNETCORE_ENVIRONMENT=Staging;DTE_BUILD_STRING=DEV-${{ github.run_number }}-${{ github.run_id }};AwsSecretsManagerSettings__Region=eu-west-2;AwsSecretsManagerSettings__SecretName=crnccd-secret-dev-rds-aurora-mysql-dte-stream-s" --function-publish true

      - name: Update alias to point to new version
        run: |
          VERSION=$(aws lambda list-versions-by-function --function-name crnccd-lambda-dev-dte-participant-stream --query "Versions[-1]" | jq -r .Version)
          aws lambda update-alias --function-name crnccd-lambda-dev-dte-participant-stream --name main --function-version $VERSION

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stream-handler-artifact
          path: ./BPOR/BPOR.Registration.Stream.Handler/src/BPOR.Registration.Stream.Handler/bin/Release/net8.0/publish/
          overwrite: true
          include-hidden-files: true
  
  QA_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BPOR
    needs: dev_build_test_deploy
    environment: QA
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          name: stream-handler-artifact
          path: BPOR.Registration.Stream.Handler/src/BPOR.Registration.Stream.Handler/bin/Release/net8.0/publish/
          overwrite: true
      - name: Configure AWS credentials - All
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.NIHR_GITHUB_ACTIONS_IAM_ID }}
          aws-secret-access-key: ${{ secrets.NIHR_GITHUB_ACTIONS_IAM_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Add Nuget Source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pa-nihr-crn/index.json"

      - name: Deploy
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet lambda deploy-function --region ${{ secrets.AWS_REGION }} -pl ./BPOR.Registration.Stream.Handler/src/BPOR.Registration.Stream.Handler crnccd-lambda-test-dte-participant-stream --function-role crnccd-iam-test-dte-role -ev "ASPNETCORE_ENVIRONMENT=Staging;DTE_BUILD_STRING=test-${{ github.run_number }}-${{ github.run_id }};;AwsSecretsManagerSettings__Region=eu-west-2;AwsSecretsManagerSettings__SecretName=crnccd-secret-test-rds-aurora-mysql-dte-stream-s" --function-publish true

      - name: Update alias to point to new version
        run: |
          VERSION=$(aws lambda list-versions-by-function --function-name crnccd-lambda-test-dte-participant-stream --query "Versions[-1]" | jq -r .Version)
          aws lambda update-alias --function-name crnccd-lambda-test-dte-participant-stream --name main --function-version $VERSION
  
  UAT_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BPOR
    needs: QA_deploy
    environment: UAT
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          name: stream-handler-artifact
          path: BPOR.Registration.Stream.Handler/src/BPOR.Registration.Stream.Handler/bin/Release/net8.0/publish/
          overwrite: true
      - name: Configure AWS credentials - All
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CRNCC_STAGING_IAM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CRNCC_STAGING_IAM_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Add Nuget Source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pa-nihr-crn/index.json"

      - name: Deploy
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet lambda deploy-function --region ${{ secrets.AWS_REGION }} -pl ./BPOR.Registration.Stream.Handler/src/BPOR.Registration.Stream.Handler crnccs-lambda-uat-dte-participant-stream --function-role crnccs-iam-uat-dte-role -ev "ASPNETCORE_ENVIRONMENT=Staging;DTE_BUILD_STRING=UAT-${{ github.run_number }}-${{ github.run_id }};;AwsSecretsManagerSettings__Region=eu-west-2;AwsSecretsManagerSettings__SecretName=crnccs-secret-uat-rds-aurora-mysql-dte-stream-s" --function-publish true

      - name: Update alias to point to new version
        run: |
          VERSION=$(aws lambda list-versions-by-function --function-name crnccs-lambda-uat-dte-participant-stream --query "Versions[-1]" | jq -r .Version)
          aws lambda update-alias --function-name crnccs-lambda-uat-dte-participant-stream --name main --function-version $VERSION
  
  OAT_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BPOR
    needs: UAT_deploy
    environment: OAT
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          name: stream-handler-artifact
          path: BPOR.Registration.Stream.Handler/src/BPOR.Registration.Stream.Handler/bin/Release/net8.0/publish/
          overwrite: true
      - name: Configure AWS credentials - All
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CRNCC_PROD_IAM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CRNCC_PROD_IAM_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Add Nuget Source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pa-nihr-crn/index.json"

      - name: Deploy
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet lambda deploy-function --region ${{ secrets.AWS_REGION }} -pl ./BPOR.Registration.Stream.Handler/src/BPOR.Registration.Stream.Handler crnccp-lambda-oat-dte-participant-stream --function-role crnccp-iam-oat-dte-role -ev "ASPNETCORE_ENVIRONMENT=Staging;DTE_BUILD_STRING=OAT-${{ github.run_number }}-${{ github.run_id }};;AwsSecretsManagerSettings__Region=eu-west-2;AwsSecretsManagerSettings__SecretName=crnccp-secret-oat-rds-aurora-mysql-dte-stream-s" --function-publish true

      - name: Update alias to point to new version
        run: |
          VERSION=$(aws lambda list-versions-by-function --function-name crnccp-lambda-oat-dte-participant-stream --query "Versions[-1]" | jq -r .Version)
          aws lambda update-alias --function-name crnccp-lambda-oat-dte-participant-stream --name main --function-version $VERSION
  
  PROD_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BPOR
    needs: OAT_deploy
    environment: PROD
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          name: stream-handler-artifact
          path: BPOR.Registration.Stream.Handler/src/BPOR.Registration.Stream.Handler/bin/Release/net8.0/publish/
          overwrite: true
      - name: Configure AWS credentials - All
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CRNCC_PROD_IAM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CRNCC_PROD_IAM_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Add Nuget Source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pa-nihr-crn/index.json"

      - name: Deploy
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet lambda deploy-function --region ${{ secrets.AWS_REGION }} -pl ./BPOR.Registration.Stream.Handler/src/BPOR.Registration.Stream.Handler crnccp-lambda-prod-dte-participant-stream --function-role crnccp-iam-prod-dte-role -ev "ASPNETCORE_ENVIRONMENT=Production;DTE_BUILD_STRING=PROD-${{ github.run_number }}-${{ github.run_id }};;AwsSecretsManagerSettings__Region=eu-west-2;AwsSecretsManagerSettings__SecretName=crnccp-secret-prod-rds-aurora-mysql-dte-stream-s" --function-publish true

      - name: Update alias to point to new version
        run: |
          VERSION=$(aws lambda list-versions-by-function --function-name crnccp-lambda-prod-dte-participant-stream --query "Versions[-1]" | jq -r .Version)
          aws lambda update-alias --function-name crnccp-lambda-prod-dte-participant-stream --name main --function-version $VERSION
